baseURL = "https://brenohildebrand.com/"
languageCode = "en-us"
title = "Breno Hildebrand"
theme = "PaperMod"
paginate = 10

[params]
  author = "Your Name"
  description = "My personal blog"
  defaultTheme = "auto"   # auto, light, dark
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true

[params.homeInfoParams]
  Title = "Hacker by day, dancer by night."
  Content = "Breaking web apps and writing about it."

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/yourusername"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
